kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-postgress
  namespace: sonarqube
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/mousam3/presist-sonar"